name: multiple_result
description: Multiple results for flutter. Inspired by dartz's Either
version: 1.0.1
author: higorlapaa@gmail.com
homepage: https://github.com/higorlapa/result

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: any
  effective_dart: ^1.3.1
